main: speedhunt.code.SpeedrunVsHunterPlugin
name: SpeedrunnerVsHunter
version: 1
api-version: 1.19
description: >
  Speedrunner vs hunter type game
commands:
  start:
    description: >
      Begin game
