runners:
  type: player_list
headstart_minutes:
  type: double
  default: 0.5
  min: 0
  max: 20
bed_explosion_damage:
  type: enum
  default: enabled
  options:
    - enabled
    - nerfed
    - disabled
auto_compass:
  type: boolean
  default: false
nether_compass:
  type: boolean
  default: true