name: Build and Release
on: [push]
jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Jar
      run: echo Build Jar here
      
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: speedrunnerVsHunter  # This folder should contain only the Jar file
        container_name: www
        account_name: saggyresourcepack
        sas_token: ${{ secrets.StorageSAS }}
        overwrite: 'true'
